# Use Node.js for building React
FROM node:22-alpine

# Set working directory
WORKDIR /app

# Install dependencies
COPY frontend/package.json frontend/package-lock.json ./
RUN npm install
COPY frontend/ .
EXPOSE 5173

# Command to run the React app
CMD ["npm", "run", "dev", "--", "--host"]