services:
  - type: web
    name: heart-backend
    env: docker
    dockerfilePath: backend/Dockerfile.backend
    plan: starter
    autoDeploy: true
  - type: web
    name: heart-frontend
    env: docker
    dockerfilePath: frontend/Dockerfile.frontend
    plan: starter
    port: 80
    autoDeploy: true