services:
  # ─── Backend (still a Docker service) ──────────────────────────────
  - type: web
    runtime: docker
    name: heart-backend
    plan: starter
    dockerfilePath: backend/Dockerfile.backend
    autoDeploy: true

  # ─── Frontend (as a Static Site) ─────────────────────────────────
  - type: static_site
    name: heart-frontend
    env: static
    plan: free
    rootDir: frontend
    buildCommand: "npm install && npm run build"
    staticPublishPath: dist
    autoDeploy: true
