services:
  # ─── Backend (Docker Web Service) ───────────────────────────────
  - type: web
    name: heart-backend
    runtime: docker
    plan: starter
    dockerfilePath: backend/Dockerfile.backend
    autoDeploy: true

  # ─── Frontend (Static Site—always free) ──────────────────────────
  - type: web
    name: heart-frontend
    runtime: static
    rootDir: frontend
    buildCommand: "npm install && npm run build"
    staticPublishPath: dist
    autoDeploy: true

    envVars:
      - key: VITE_BACKEND_URL
        value: "https://heart-backend-egtw.onrender.com"
    
    routes:
      - type: rewrite
        source: /api/*
        destination: https://heart-backend-xxxxx.onrender.com/api/*