services:
  - type: web
    name: heart-backend
    env: docker
    dockerfilePath: backend/Dockerfile.backend
    plan: free
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
  
  - type: web
    name: heart-frontend
    env: docker
    dockerfilePath: frontend/Dockerfile.frontend
    plan: free
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production