services:
  - type: web
    name: heart-backend
    env: docker
    dockerfilePath: backend/Dockerfile
    plan: starter
    autoDeploy: true
  - type: static
    name: heart-frontend
    buildCommand: "npm install && npm run build"
    publishDir: dist
    rootDir: frontend
    autoDeploy: true
