services:
  - type: web
    name: heart-backend
    env: docker
    dockerfilePath: backend/Dockerfile
    plan: starter
    autoDeploy: true

  - type: static
    name: heart-frontend
    env: static
    rootDir: frontend
    buildCommand: "npm install && npm run build"
    publishPath: dist
    autoDeploy: true
