services:
  # ─── Backend ─────────────────────────────────────────────────────────
  - type: web
    name: heart-backend
    runtime: docker
    plan: free
    dockerfilePath: backend/Dockerfile.backend
    autoDeploy: true
    # (optional) if your app needs env vars:
    envVars:
      - key: SECRET_KEY
        fromDatabase: SECRET_KEY

  # ─── Frontend ────────────────────────────────────────────────────────
  - type: web
    name: heart-frontend
    runtime: docker
    plan: free
    dockerfilePath: frontend/Dockerfile.frontend
    autoDeploy: true
