services:
  # ─── Backend ─────────────────────────────────────────────────────────
  - type: web
    name: heart-backend
    runtime: docker
    plan: free
    dockerfilePath: backend/Dockerfile.backend
    autoDeploy: true

  # ─── Frontend ────────────────────────────────────────────────────────
  - type: web
    name: heart-frontend
    runtime: docker
    plan: free
    dockerfilePath: frontend/Dockerfile.frontend
    autoDeploy: true
