services:
  # ─── Backend (Docker Web Service) ───────────────────────────────
  - type: web
    name: heart-backend
    runtime: docker
    plan: starter
    dockerfilePath: backend/Dockerfile.backend
    autoDeploy: true

  # ─── Frontend (Static Site) ────────────────────────────────────
  - type: web
    name: heart-frontend
    env: static
    plan: free
    rootDir: frontend
    buildCommand: "npm install && npm run build"
    staticPublishPath: dist
    autoDeploy: true